services:
  - type: web
    name: zynochat-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
